### ISSUE TITLE
Support for SSML

### ISSUE THREAD

**Issue by Colpan** [damianFC/alexa-rubykit#11]
Hi there!
I've been using this gem for a project and really appreciate the work you guys have done.

Looking at the source code for responses (https://github.com/damianFC/alexa-rubykit/blob/master/lib/alexa_rubykit/response.rb) it doesn't seem like there is support for SSML (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference).

I just wanted to be sure that I am not missing anything. If it is in fact the case that it isn't currently supported, I don't mind creating a PR to add support. :)

Let me know! Thanks!

**Comment by damianFC** [comment]
Hey there

I haven't updated the gem to support the SSML, if you have a patch I'd love to take a look and possibly merge in :)

This gem is a personal project so if you'd like to contribute feel free to submit a PR!

**Comment by Colpan** [comment]
Cool. I'll probably take a crack at it tomorrow and submit a PR when I've got something.

Cheers!

**Comment by damianFC** [comment]
Merged

Thank you so much for this, I also pushed a new version of the gem!

Closing this issue
