### ISSUE TITLE
send echo data?

### ISSUE THREAD

**Issue by cj** [damianFC/alexa-rubykit#2]
@damianFC thanks for this gem.  I can't wait to try it out once I get accepted into the developer beta.  Quick question, can you send echo data without the person starting the request first?  i.e. to send notifications of @mentions in github/slack.

**Comment by damianf-r7** [comment]
Hey @cj No, so far the user has to initiate every request, there's is a re-prompt option that came out in a newer version but the user always to initiate.

Let us know what you build! Would love to see examples or contributions.

**Comment by damianFC** [comment]
hey @cj No, as far as I know there is no option to do that, a user always has to initiate the connection. There is a re-prompt option that was just added but nothing out yet.

Let us know what you build!

**Comment by cj** [comment]
Well, lets hope they add the option to send notifications.  I can think of a lot of useful applications, that I would use on a daily basis if it was possible.

I'll keep you posted :smile:

**Comment by cj** [comment]
@damianFC how's it going?  I just noticed that spotify allows you to use echo as a speaker now.  I'm guessing that means you can send things?
