### ISSUE TITLE
New gem version

### ISSUE THREAD

**Issue by kjanoudi-spindance** [damianFC/alexa-rubykit#6]
Hey - it looks like there have been quite a few changes since the last gem release. Any plans to update the gem?

**Comment by kjanoudi-spindance** [comment]
PS - how does this line work, where is `value` from? https://github.com/damianFC/alexa-rubykit/blob/v1.1.0/lib/alexa_rubykit/intent_request.rb#L27

**Comment by kjanoudi-spindance** [comment]
@damianFC  hello, anyone there?

**Comment by damianFC** [comment]
Pushed to github, but I lost access to my rubygems and trying to get it back. Apologies my dev laptop had died.

**Comment by damianFC** [comment]
Finally got my access back to rubygems and pushed an update to the gem with all the changes.
